services:
  db:
    image: postgres:16-alpine
    container_name: jobview-db
    restart: no
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - jobview-db:/var/lib/postgresql/data

volumes:
  jobview-db: